FROM python:3.9

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend
COPY shared ./shared

ENV PYTHONPATH=/app:/app/shared

CMD ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]