FROM python:3.9

WORKDIR /app

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*
    
COPY worker/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY worker ./worker
COPY shared ./shared

ENV PYTHONPATH=/app:/app/shared

CMD ["uvicorn", "worker.app.main:app", "--host", "0.0.0.0", "--port", "8000"]