"""update models

Revision ID: 24e728496601
Revises: 737f58beae3b
Create Date: 2025-06-13 01:12:40.895652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e728496601'
down_revision: Union[str, None] = '737f58beae3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('score_in_percentage', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('interview_cleared_by_candidate', sa.String(), nullable=True))
    op.drop_column('question_answers', 'ai_remark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_answers', sa.Column('ai_remark', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('interviews', 'interview_cleared_by_candidate')
    op.drop_column('interviews', 'score_in_percentage')
    # ### end Alembic commands ###
