"""Initial migration

Revision ID: 737f58beae3b
Revises: f6828ddbb213
Create Date: 2025-06-08 21:24:15.151568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737f58beae3b'
down_revision: Union[str, None] = 'f6828ddbb213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jd_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('resume_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('jd_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('resume_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_status')
    op.drop_column('users', 'jd_status')
    op.drop_column('users', 'resume_text')
    op.drop_column('users', 'jd_text')
    # ### end Alembic commands ###
