"""update models

Revision ID: d6ddfe3e5d61
Revises: 24e728496601
Create Date: 2025-06-13 01:20:30.341303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ddfe3e5d61'
down_revision: Union[str, None] = '24e728496601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_answers', sa.Column('ai_remark', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_answers', 'ai_remark')
    # ### end Alembic commands ###
